- name: set swap_file variable
  set_fact:
    swap_file: /{{ swap_space }}.swap

- name: check if swap file exists
  stat:
    path: '{{ swap_file }}'
  register: swap_file_check

- name: create swap file
  become: yes
  command: fallocate -l {{ swap_space }} {{ swap_file }}
  when: not swap_file_check.stat.exists

- name: Create swap space
  command: dd if=/dev/zero of=/extraswap bs=1M count=512
  when: not swap_file_check.stat.exists

- name: set permissions on swap file
  become: yes
  file:
    path: '{{ swap_file }}'
    mode: 0600

- name: format swap file
  become: yes
  command: mkswap {{ swap_file }}
  when: not swap_file_check.stat.exists

- name: add to fstab
  become: yes
  lineinfile:
    dest: /etc/fstab
    regexp: '{{ swap_file }}'
    line: '{{ swap_file }} none swap sw 0 0'

- name: turn on swap
  become: yes
  command: swapon -a

- name: set swapiness
  become: yes
  sysctl:
    name: vm.swappiness
    value: '1'
