cronjobs:
    - name: "clear-sessions"
      schedule: "20 5 * * *" # 5:20 AM every day
      command: "{{ manage_cmd }} clearsessions"

    - name: "create-recommendations"
      schedule: "20 4 * * *" # 4:20 AM every day
      command: "{{ manage_cmd }} create_recommendations"

    - name: "fetch-top-itunes"
      schedule: "15 3 * * *" # 3:15 AM every day
      command: "{{ manage_cmd }} fetch_top_itunes"

    - name: "parse-feeds"
      schedule: "*/6 * * * *" # Every 6 minutes
      command: "{{ manage_cmd }} parse_feeds"

    - name: "prune-db-task-results"
      schedule: "25 6 * * *" # 6:25 AM every day
      command: "{{ manage_cmd }} prune_db_task_results --min-age-days=1"

    - name: "send-notifications"
      schedule: "0 13 * * 1" # 1:00 PM every Monday
      command: "{{ manage_cmd }} send_notifications"

    - name: "send-recommendations"
      schedule: "0 13 * * 5" # 1:00 PM every Friday
      command: "{{ manage_cmd }} send_recommendations"
