cronjobs:
    - name: "clear-sessions"
      schedule: "20 5 * * *" # 5:20 AM every day
      command: "{{ manage_cmd }} clearsessions"

    - name: "create-recommendations"
      schedule: "20 4 * * *" # 4:20 AM every day
      command: "{{ manage_cmd }} create_podcast_recommendations"

    - name: "fetch-itunes"
      schedule: "15 3 * * *" # 3:15 AM every day
      command: "{{ manage_cmd }} fetch_itunes_feeds"

    - name: "parse-feeds"
      schedule: "*/6 * * * *" # Every 6 minutes
      command: "{{ manage_cmd }} parse_podcast_feeds"

    - name: "send-notifications"
      schedule: "0 13 * * 1" # 1:00 PM every Monday
      command: "{{ manage_cmd }} send_episode_updates"

    - name: "send-recommendations"
      schedule: "0 13 * * 5" # 1:00 PM every Friday
      command: "{{ manage_cmd }} send_podcast_recommendations"
